spring.application.name=class3

#spring.datasource.url=jdbc:mysql://database-aws-class.c1syy0o6ybcv.us-east-2.rds.amazonaws.com:3306/awsclass?sslMode=REQUIRED
#spring.datasource.username=admin
#spring.datasource.password=yasmin1234

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
